# Generated by Django 4.2.2 on 2025-04-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
