# Generated by Django 4.2.2 on 2025-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_loginattempt_rename_verificationcode_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
